const UPDATE_GEOCOORDINATES = 'UPDATE_GEOCOORDINATES';
const UPDATE_CURRENT_CITY = 'CURRENT_UPDATE_CURRENT_CITYCITY';
const TODAYS_WEATHER = 'TODAYS_WEATHER';
const FIVE_DAY_FORECAST = 'FIVE_DAY_FORECAST';
const SET_SUMMARIZED_FORECAST = 'SET_SUMMARIZED_FORECAST';
const SET_TIMEZONE = 'SET_TIMEZONE';

module.exports = {
  UPDATE_GEOCOORDINATES,
  UPDATE_CURRENT_CITY,
  TODAYS_WEATHER,
  FIVE_DAY_FORECAST,
  SET_SUMMARIZED_FORECAST,
  SET_TIMEZONE,
} 