const UPDATE_GEOCOORDINATES = 'UPDATE_GEOCOORDINATES';
const UPDATE_CURRENT_CITY = 'CURRENT_UPDATE_CURRENT_CITYCITY';
const CITY_WEATHER = 'CITY_WEATHER';

module.exports = {
  UPDATE_GEOCOORDINATES,
  UPDATE_CURRENT_CITY,
  CITY_WEATHER
} 